/**
 * data.js
 * -------------------------------------------------------------
 * Capa de "base de datos" del proyecto Dubon's.
 * En un entorno real esto vendría de una base de datos (MySQL,
 * PostgreSQL, MongoDB, etc.) consultada a través de una API.
 * Para esta feria científica, se simula esa arquitectura con un
 * arreglo de objetos que hace de "seed" inicial, y db.js se
 * encarga de persistirlo y consultarlo desde localStorage,
 * imitando el ciclo real de una app: SEED -> ALMACENAMIENTO -> CONSULTA.
 * -------------------------------------------------------------
 */

const DUBONS_SEED_VEHICULOS = [
  {
    id: "TOY-COR-25",
    marca: "Toyota",
    modelo: "Corolla",
    anio: 2025,
    precio: 24500,
    km: 0,
    condicion: "Nuevo",
    tipo: "Sedán",
    transmision: "Automática",
    combustible: "Gasolina",
    color: "#c1272d",
    potenciaHP: 139,
    traccion: "4x2",
    destacado: true,
    descripcion: "El Corolla 2025 combina eficiencia de combustible con un diseño confiable, ideal para uso diario en ciudad y carretera.",
    caracteristicas: ["Aire acondicionado", "Cámara de reversa", "Bluetooth", "Sensores de parqueo"]
  },
  {
    id: "HON-CIV-24",
    marca: "Honda",
    modelo: "Civic",
    anio: 2024,
    precio: 22800,
    km: 12500,
    condicion: "Seminuevo",
    tipo: "Sedán",
    transmision: "Automática",
    combustible: "Gasolina",
    color: "#2f6f4e",
    potenciaHP: 158,
    traccion: "4x2",
    destacado: true,
    descripcion: "Seminuevo certificado con historial de mantenimiento completo. Manejo ágil y bajo consumo de combustible.",
    caracteristicas: ["Pantalla táctil", "Apple CarPlay", "Control crucero", "Llantas de aleación"]
  },
  {
    id: "HYU-TUC-25",
    marca: "Hyundai",
    modelo: "Tucson",
    anio: 2025,
    precio: 32900,
    km: 0,
    condicion: "Nuevo",
    tipo: "SUV",
    transmision: "Automática",
    combustible: "Gasolina",
    color: "#14181f",
    potenciaHP: 187,
    traccion: "4x4",
    destacado: true,
    descripcion: "SUV familiar con amplio espacio de carga, tracción 4x4 y las últimas ayudas de seguridad activa.",
    caracteristicas: ["Techo panorámico", "Frenado de emergencia", "Cámaras 360°", "Asientos en piel"]
  },
  {
    id: "KIA-SPO-23",
    marca: "Kia",
    modelo: "Sportage",
    anio: 2023,
    precio: 27400,
    km: 28900,
    condicion: "Seminuevo",
    tipo: "SUV",
    transmision: "Automática",
    combustible: "Gasolina",
    color: "#f4b400",
    potenciaHP: 181,
    traccion: "4x2",
    destacado: false,
    descripcion: "SUV en excelente estado, un solo dueño, ideal para familia. Revisión mecánica de 120 puntos aprobada.",
    caracteristicas: ["Sensores de punto ciego", "Bluetooth", "Aire acondicionado dual", "Cámara de reversa"]
  },
  {
    id: "NIS-VER-25",
    marca: "Nissan",
    modelo: "Versa",
    anio: 2025,
    precio: 18900,
    km: 0,
    condicion: "Nuevo",
    tipo: "Sedán",
    transmision: "CVT",
    combustible: "Gasolina",
    color: "#6b7280",
    potenciaHP: 122,
    traccion: "4x2",
    destacado: false,
    descripcion: "El sedán ideal para empezar: económico, espacioso y con bajo costo de mantenimiento.",
    caracteristicas: ["Aire acondicionado", "Bluetooth", "Vidrios eléctricos", "Alarma"]
  },
  {
    id: "MAZ-CX5-22",
    marca: "Mazda",
    modelo: "CX-5",
    anio: 2022,
    precio: 26900,
    km: 41200,
    condicion: "Seminuevo",
    tipo: "SUV",
    transmision: "Automática",
    combustible: "Gasolina",
    color: "#c1272d",
    potenciaHP: 187,
    traccion: "4x4",
    destacado: false,
    descripcion: "Diseño Kodo, manejo deportivo e interior premium. Servicio de agencia al día.",
    caracteristicas: ["Head-up display", "Asientos calefaccionados", "BOSE Audio", "Tracción 4x4"]
  },
  {
    id: "CHV_SIL-24",
    marca: "Chevrolet",
    modelo: "Silverado",
    anio: 2024,
    precio: 41500,
    km: 8200,
    condicion: "Seminuevo",
    tipo: "Pick Up",
    transmision: "Automática",
    combustible: "Diésel",
    color: "#14181f",
    potenciaHP: 277,
    traccion: "4x4",
    destacado: true,
    descripcion: "Pick up robusta para trabajo y aventura, con capacidad de carga y remolque líderes en su clase.",
    caracteristicas: ["Caja de 8 velocidades", "Cámara de remolque", "Control de descenso", "Doble cabina"]
  },
  {
    id: "FOR_RAN-23",
    marca: "Ford",
    modelo: "Ranger",
    anio: 2023,
    precio: 33900,
    km: 22000,
    condicion: "Seminuevo",
    tipo: "Pick Up",
    transmision: "Automática",
    combustible: "Diésel",
    color: "#f4b400",
    potenciaHP: 197,
    traccion: "4x4",
    destacado: false,
    descripcion: "Ideal para trabajo pesado o fin de semana en el campo, con excelente respaldo de repuestos en Guatemala.",
    caracteristicas: ["Modo 4x4 bloqueable", "Pantalla SYNC", "Barras antivuelco", "Cama de carga forrada"]
  },
  {
    id: "MIT_XPD-25",
    marca: "Mitsubishi",
    modelo: "Xpander",
    anio: 2025,
    precio: 23900,
    km: 0,
    condicion: "Nuevo",
    tipo: "Microbús",
    transmision: "CVT",
    combustible: "Gasolina",
    color: "#2f6f4e",
    potenciaHP: 104,
    traccion: "4x2",
    destacado: false,
    descripcion: "Espacio para 7 pasajeros, ideal para familias grandes que buscan comodidad sin sacrificar economía.",
    caracteristicas: ["7 pasajeros", "Aire acondicionado trasero", "USB en 2da y 3ra fila", "Cámara de reversa"]
  },
  {
    id: "TOY_HIL-22",
    marca: "Toyota",
    modelo: "Hilux",
    anio: 2022,
    precio: 29900,
    km: 55000,
    condicion: "Seminuevo",
    tipo: "Pick Up",
    transmision: "Mecánica",
    combustible: "Diésel",
    color: "#6b7280",
    potenciaHP: 163,
    traccion: "4x4",
    destacado: false,
    descripcion: "La legendaria confiabilidad Toyota, con historial verificado y llantas nuevas incluidas.",
    caracteristicas: ["4x4 mecánico", "Barra de protección", "Radio con Bluetooth", "Doble cabina"]
  },
  {
    id: "HYU_ACC-21",
    marca: "Hyundai",
    modelo: "Accent",
    anio: 2021,
    precio: 15900,
    km: 62300,
    condicion: "Seminuevo",
    tipo: "Sedán",
    transmision: "Automática",
    combustible: "Gasolina",
    color: "#c1272d",
    potenciaHP: 123,
    traccion: "4x2",
    destacado: false,
    descripcion: "Opción económica y confiable para moverte en la ciudad, con bajo kilometraje para su año.",
    caracteristicas: ["Aire acondicionado", "Vidrios eléctricos", "Bluetooth", "Rines de lujo"]
  },
  {
    id: "KIA_PIC-25",
    marca: "Kia",
    modelo: "Picanto",
    anio: 2025,
    precio: 14500,
    km: 0,
    condicion: "Nuevo",
    tipo: "Hatchback",
    transmision: "Mecánica",
    combustible: "Gasolina",
    color: "#f4b400",
    potenciaHP: 83,
    traccion: "4x2",
    destacado: false,
    descripcion: "Compacto, ágil y con el menor costo de mantenimiento de la marca. Perfecto primer auto.",
    caracteristicas: ["Aire acondicionado", "Radio Bluetooth", "Dirección asistida", "Bajo consumo"]
  },
  {
    id: "BYD_SEA-26",
    marca: "BYD",
    modelo: "Seal",
    anio: 2026,
    precio: 37900,
    km: 0,
    condicion: "Nuevo",
    tipo: "Sedán",
    transmision: "Automática",
    combustible: "Eléctrico",
    color: "#2f6f4e",
    potenciaHP: 308,
    traccion: "AWD",
    destacado: true,
    descripcion: "Sedán 100% eléctrico con aceleración deportiva y cero emisiones. El futuro ya está en Dubon's.",
    caracteristicas: ["Autonomía 520km", "Carga rápida", "Piloto automático adaptativo", "Interior full digital"]
  },
  {
    id: "SUB_FOR-23",
    marca: "Subaru",
    modelo: "Forester",
    anio: 2023,
    precio: 28900,
    km: 19500,
    condicion: "Seminuevo",
    tipo: "SUV",
    transmision: "CVT",
    combustible: "Gasolina",
    color: "#14181f",
    potenciaHP: 182,
    traccion: "AWD",
    destacado: false,
    descripcion: "Tracción integral simétrica de serie, ideal para carreteras de montaña. Excelente visibilidad.",
    caracteristicas: ["AWD de serie", "EyeSight seguridad", "Techo corredizo", "Rieles de techo"]
  },
  {
    id: "MAZ_MZ3-24",
    marca: "Mazda",
    modelo: "Mazda 3",
    anio: 2024,
    precio: 21900,
    km: 9800,
    condicion: "Seminuevo",
    tipo: "Hatchback",
    transmision: "Automática",
    combustible: "Gasolina",
    color: "#6b7280",
    potenciaHP: 155,
    traccion: "4x2",
    destacado: false,
    descripcion: "Diseño premiado, manejo preciso e interior de calidad superior a su segmento.",
    caracteristicas: ["Pantalla 8.8''", "Sonido premium", "Frenado autónomo", "Asientos deportivos"]
  },
  {
    id: "RAM_150-24",
    marca: "RAM",
    modelo: "1500",
    anio: 2024,
    precio: 45900,
    km: 15200,
    condicion: "Seminuevo",
    tipo: "Pick Up",
    transmision: "Automática",
    combustible: "Gasolina",
    color: "#c1272d",
    potenciaHP: 305,
    traccion: "4x4",
    destacado: false,
    descripcion: "Pick up de lujo con suspensión neumática e interior digno de una SUV premium.",
    caracteristicas: ["Suspensión neumática", "Pantalla 12''", "Asientos ventilados", "Caja de 8 velocidades"]
  }
];
